on: [push]

name: Dead code analysis

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
        with:
          flags: "-l"
